DROP DATABASE Gimnasio;
CREATE DATABASE IF NOT EXISTS Gimnasio;

USE Gimnasio;

CREATE TABLE MEMBER (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20)
);

CREATE TABLE INSTRUCTOR (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL
);

CREATE TABLE TYPES (
	ID INTEGER PRIMARY KEY,
	TYPE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE Classes(
	ID INTEGER PRIMARY KEY,
    CLASS_NAME INTEGER NOT NULL,
    TYPE_ID INTEGER NOT NULL,
    DURATION_MINS TIME NOT NULL,
    FOREIGN KEY (TYPE_ID) REFERENCES TYPES(ID)
);

CREATE TABLE Class_Schedule (
    ID INTEGER PRIMARY KEY,
    CLASS_ID INTEGER NOT NULL,
    INSTRUCTOR_ID INTEGER NOT NULL,
    STRAT_TIME DATETIME NOT NULL,
    END_TIME DATETIME NOT NULL,
    FOREIGN KEY (class_id) REFERENCES Classes(id),
    FOREIGN KEY (instructor_id) REFERENCES Instructor(id)
);

CREATE TABLE Member_Signups (
    ID INTEGER PRIMARY KEY,
    MEMBER_ID INTEGER NOT NULL,
    CLASS_SCHEDULE_ID INTEGER NOT NULL,
    NO_SHOW BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (member_id) REFERENCES Member(id),
    FOREIGN KEY (class_schedule_id) REFERENCES Class_Schedule(id)
);